### ISSUE TITLE
Неактуальная ссылка

### ISSUE THREAD

**Issue by fallofElil** [ademaro/frontend-tips#2]
Последняя ссылка в разделе "Доступность" - "Доступность веб-страницы" (https://nicothin.pro/page/dostupnost-veb-stranicy) переводит на страницу ошибки 404.

**Comment by ademaro** [comment]
Общаюсь с автором, пока тут можно почитать: http://web.archive.org/web/20171201194714/https://nicothin.pro/page/dostupnost-veb-stranicy

**Comment by ademaro** [comment]
Отлично, статья вернулась на сайт! 
@fallofElil благодарю за ишью!) Закрываю.

**Comment by fallofElil** [comment]
@ademaro отлично!)
